name: Gradle Nightly Test
on:
  schedule:
    - cron: 0 0 * * * # daily
jobs:
  nightly-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - uses: gradle/gradle-build-action@v2
      with:
        gradle-version: nightly
    - run: gradle test # just test build configuration
